### ISSUE TITLE
Oval race does not work

### ISSUE THREAD

**Issue by Inthenew** [Inthenew/Sketchbook#2]
For some reason I am getting this error when I go into the Oval race in the game:
FollowPath.ts:42 Uncaught TypeError: Cannot read properties of undefined (reading 'object')
    at ./src/ts/characters/character_ai/FollowPath.ts.FollowPath.update (FollowPath.ts:42:1)
    at ./src/ts/characters/Character.ts.Character.update (Character.ts:314:1)
    at World.ts:176:1
    at Array.forEach (<anonymous>)
    at ./src/ts/world/World.ts.World.update (World.ts:175:1)
    at ./src/ts/world/World.ts.World.render (World.ts:258:1)
    at World.ts:251:1
Imma try to fix it soon

**Comment by Inthenew** [comment]
Fixed but not pushed

**Comment by Inthenew** [comment]
Fixed and pushed now
